navigation:
  - title: Accueil
    url: /
  - title: Produits
    url: /products
  - title: Qui sommes nous ?
    url: /qui-sommes-nous
socials:
  - icon: assets/images/LAdC-amazon-rouge.svg
    url: https://amazon.fr
  - icon: assets/images/LAdC-facebook-rouge.svg
    url: https://facebook.com
  - icon: assets/images/LAdC-instagram-rouge.svg
    url: https://www.instagram.com/lartdeschauds
gamme:
  - icon: assets/images/hero.png
    url: #
    ratio: 1x2
  - icon: assets/images/hero.png
    url: #
    ratio: 1x1
  - icon: assets/images/hero.png
    url: #
    ratio: 1x1
  - icon: assets/images/LAdC_logo_c.svg
    url: #
    ratio: logo
  - icon: assets/images/hero.png
    url: #
    ratio: 1x2
  - icon: assets/images/hero.png
    url: #
    ratio: 1x1
  - icon: assets/images/hero.png
    url: #
    ratio: 1x1

