socials:
  - icon: 
    url:
  - icon: 
    url:
  - icon: 
    url:
gamme:
  - icon: assets/images/hero.png
    url: #
    ratio: 1x2
  - icon: assets/images/hero.png
    url: #
    ratio: 1x1
  - icon: assets/images/hero.png
    url: #
    ratio: 1x1
  - icon: assets/images/LAdC_logo_c_grand.png
    url: #
    ratio: logo
  - icon: assets/images/hero.png
    url: #
    ratio: 1x2
  - icon: assets/images/hero.png
    url: #
    ratio: 1x1
  - icon: assets/images/hero.png
    url: #
    ratio: 1x1

